#!/usr/bin/env node
/**
 * SEO pass: inject canonical, Open Graph image, BreadcrumbList JSON-LD, and
 * page-type-specific JSON-LD (ItemList for Top 5, Article for news / topic
 * pages) into every relevant static HTML file at the repo root and in /news.
 *
 * Idempotent: a managed block delimited by SEO_MARKER_START / SEO_MARKER_END
 * is removed and re-inserted on every run, and conflicting canonical /
 * og:image / og:url / twitter:image tags from the original templates are
 * stripped before the new ones are written. Re-run any time you add pages.
 *
 * Skips:
 *  - healthrankings-article-*.html / healthrankings-review-*.html
 *    (those URLs are redirected by middleware to dynamic Next routes that
 *    own their own metadata).
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PUBLIC_DIR = path.join(ROOT, 'apps', 'web', 'public');
const SITE = 'https://www.healthrankings.co';
const DEFAULT_OG = `${SITE}/brand/og-default.svg`;

const SEO_MARKER_START = '<!-- seo-pass:start (auto-generated by scripts/seo-pass.js) -->';
const SEO_MARKER_END = '<!-- seo-pass:end -->';

const PAGE_TYPE = {
  HOME: 'home',
  DEVICE_HUB: 'deviceHub',
  ARTICLE_HUB: 'articleHub',
  CONDITION_HUB: 'conditionHub',
  NEWS_HUB: 'newsHub',
  ABOUT: 'about',
  CONTACT: 'contact',
  TOP5: 'top5',
  CATALOG: 'catalog',
  CONDITION: 'condition',
  NEWS_ARTICLE: 'newsArticle',
  ERROR: 'errorPage',
  OTHER: 'other',
};

function listTargetFiles() {
  const out = [];
  for (const name of fs.readdirSync(ROOT)) {
    if (!name.endsWith('.html')) continue;
    if (/^healthrankings-article-/i.test(name)) continue;
    if (/^healthrankings-review-/i.test(name)) continue;
    const abs = path.join(ROOT, name);
    if (!fs.statSync(abs).isFile()) continue;
    out.push({ abs, rel: name, scope: 'root' });
  }
  const newsDir = path.join(ROOT, 'news');
  if (fs.existsSync(newsDir)) {
    for (const name of fs.readdirSync(newsDir)) {
      if (!name.endsWith('.html')) continue;
      const abs = path.join(newsDir, name);
      if (!fs.statSync(abs).isFile()) continue;
      out.push({ abs, rel: name, scope: 'news' });
    }
  }
  return out;
}

function detectPageType(file) {
  if (file.scope === 'news') return PAGE_TYPE.NEWS_ARTICLE;
  const f = file.rel;
  if (f === 'index.html' || f === 'healthrankings-homepage.html') return PAGE_TYPE.HOME;
  if (f === 'healthrankings-devices.html') return PAGE_TYPE.DEVICE_HUB;
  if (f === 'healthrankings-articles.html') return PAGE_TYPE.ARTICLE_HUB;
  if (f === 'healthrankings-conditions.html') return PAGE_TYPE.CONDITION_HUB;
  if (f === 'healthrankings-news.html') return PAGE_TYPE.NEWS_HUB;
  if (f === 'healthrankings-about.html') return PAGE_TYPE.ABOUT;
  if (f === 'healthrankings-contact.html') return PAGE_TYPE.CONTACT;
  if (f === '404.html') return PAGE_TYPE.ERROR;
  if (/-top5\.html$/i.test(f)) return PAGE_TYPE.TOP5;
  if (/^healthrankings-all-/i.test(f)) return PAGE_TYPE.CATALOG;
  if (/^healthrankings-news-/i.test(f)) return PAGE_TYPE.NEWS_ARTICLE;
  if (/^healthrankings-/i.test(f)) return PAGE_TYPE.CONDITION;
  return PAGE_TYPE.OTHER;
}

function urlFor(file) {
  if (file.scope === 'news') return `${SITE}/news/${file.rel}`;
  if (file.rel === 'index.html' || file.rel === 'healthrankings-homepage.html') return `${SITE}/`;
  return `${SITE}/${file.rel}`;
}

function decodeBasicHtml(s) {
  return String(s || '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#x27;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/&middot;/g, '·');
}

function escAttr(s) {
  return String(s || '').replace(/&/g, '&amp;').replace(/"/g, '&quot;');
}

function stripHtmlTags(s) {
  return decodeBasicHtml(String(s || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim());
}

function extractTitle(html) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  if (!m) return '';
  return decodeBasicHtml(m[1].trim());
}

function extractMetaDescription(html) {
  const m = html.match(/<meta\s+name="description"\s+content="([^"]*)"/i);
  return m ? decodeBasicHtml(m[1]) : '';
}

function extractH1(html) {
  const m = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  return m ? stripHtmlTags(m[1]) : '';
}

function extractFirstImage(html) {
  // Prefer hero or featured images; fall back to first non-decorative <img>
  const heroM = html.match(/<img[^>]+(?:hero|featured|product)[^>]+src="([^"]+\.(?:png|jpe?g|webp|svg))"/i);
  if (heroM) return heroM[1];
  const anyM = html.match(/<img[^>]+src="([^"]+\.(?:png|jpe?g|webp|svg))"/i);
  return anyM ? anyM[1] : null;
}

/**
 * Best-effort extract of product names from a Top 5 page. Targets the most common
 * structures used across templates: rank cards with <h2>/<h3>/<h4> titles
 * containing the product name, optionally inside <a> wrappers.
 */
function extractTop5Products(html) {
  const products = [];
  const seen = new Set();
  const patterns = [
    // Card title classes commonly used across templates
    /<h[2-4][^>]*class="[^"]*(?:product-name|review-title|top5-name|card-title|product-title|rank-title|winner-title|review-card-title|card-product-name)[^"]*"[^>]*>([\s\S]*?)<\/h[2-4]>/gi,
    // Generic rank card structure: <div class="rank-card"> ... <h3>Name</h3>
    /<(?:article|div)[^>]*class="[^"]*(?:rank-card|product-card|review-card|top5-card)[^"]*"[^>]*>[\s\S]*?<h[2-4][^>]*>([\s\S]*?)<\/h[2-4]>/gi,
  ];
  for (const re of patterns) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(html)) && products.length < 5) {
      const name = stripHtmlTags(m[1]);
      if (!name || name.length < 3) continue;
      if (seen.has(name.toLowerCase())) continue;
      seen.add(name.toLowerCase());
      products.push(name);
    }
    if (products.length >= 5) break;
  }
  return products;
}

function deriveCleanTitle(rawTitle) {
  return decodeBasicHtml(rawTitle).replace(/\s*\|\s*HealthRankings.*$/i, '').trim();
}

function buildBreadcrumb(file, pageType, displayTitle) {
  const items = [{ name: 'Home', url: `${SITE}/` }];
  if (pageType === PAGE_TYPE.TOP5 || pageType === PAGE_TYPE.CATALOG || pageType === PAGE_TYPE.CONDITION) {
    items.push({ name: 'Devices', url: `${SITE}/healthrankings-devices.html` });
  }
  if (pageType === PAGE_TYPE.NEWS_ARTICLE || pageType === PAGE_TYPE.NEWS_HUB) {
    if (pageType === PAGE_TYPE.NEWS_ARTICLE) {
      items.push({ name: 'News', url: `${SITE}/healthrankings-news.html` });
    }
  }
  if (pageType === PAGE_TYPE.ARTICLE_HUB) {
    // Final breadcrumb is the hub itself; no intermediate.
  }
  if (pageType === PAGE_TYPE.CONDITION_HUB) {
    // Final breadcrumb is the hub.
  }
  if (
    pageType !== PAGE_TYPE.HOME &&
    pageType !== PAGE_TYPE.ERROR
  ) {
    items.push({ name: displayTitle, url: urlFor(file) });
  }
  if (items.length < 2) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((it, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: it.name,
      item: it.url,
    })),
  };
}

function buildItemList(file, displayTitle, products, description) {
  if (!products || !products.length) return null;
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: displayTitle,
    url: urlFor(file),
    numberOfItems: products.length,
    description: description || undefined,
    itemListElement: products.map((p, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: p,
    })),
  };
}

function buildArticleSchema(file, displayTitle, description, image) {
  const url = urlFor(file);
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: displayTitle.slice(0, 110),
    description: description ? description.slice(0, 240) : undefined,
    url,
    image: image || DEFAULT_OG,
    publisher: {
      '@type': 'Organization',
      name: 'HealthRankings',
      url: `${SITE}/`,
      logo: { '@type': 'ImageObject', url: `${SITE}/brand/og-default.svg` },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
  };
}

function buildCollectionSchema(file, displayTitle, description) {
  const url = urlFor(file);
  return {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: displayTitle,
    url,
    description: description || undefined,
    isPartOf: { '@type': 'WebSite', name: 'HealthRankings', url: `${SITE}/` },
  };
}

/**
 * Add alt fallback to <img> tags that are missing one or have empty alt.
 * Heuristic: walk through the file, track the most recent <h1>/<h2>/<h3>/<h4>
 * text, and use it as alt when an image has no usable alt. Skip very small or
 * decorative SVG-style placeholders by leaving alt="" untouched on inline SVG
 * (this regex only targets <img>).
 */
function fillImageAltText(html, fallbackAlt) {
  let mostRecentHeading = fallbackAlt || '';
  // Build a tiny tokenizer: split on <img...> or <hN>...</hN> boundaries.
  const tokenRe = /<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>|<img\b[^>]*>/gi;
  return html.replace(tokenRe, (match, headingInner) => {
    if (headingInner !== undefined) {
      const t = stripHtmlTags(headingInner);
      if (t) mostRecentHeading = t;
      return match;
    }
    if (!/^<img\b/i.test(match)) return match;
    const altMatch = match.match(/\salt\s*=\s*"([^"]*)"/i);
    const has = altMatch && altMatch[1].trim().length > 0;
    if (has) return match;
    const altText = (mostRecentHeading || fallbackAlt || 'HealthRankings').slice(0, 140);
    if (altMatch) {
      return match.replace(/\salt\s*=\s*"[^"]*"/i, ` alt="${escAttr(altText)}"`);
    }
    return match.replace(/<img\b/i, `<img alt="${escAttr(altText)}"`);
  });
}

function buildInjectionBlock({ canonicalUrl, ogImage, jsonLdBlocks }) {
  const lines = [SEO_MARKER_START];
  lines.push(`<link rel="canonical" href="${escAttr(canonicalUrl)}">`);
  lines.push(`<meta property="og:url" content="${escAttr(canonicalUrl)}">`);
  lines.push(`<meta property="og:image" content="${escAttr(ogImage)}">`);
  lines.push(`<meta name="twitter:image" content="${escAttr(ogImage)}">`);
  for (const block of jsonLdBlocks) {
    if (!block) continue;
    lines.push(
      `<script type="application/ld+json">${JSON.stringify(block).replace(/</g, '\\u003c')}</script>`
    );
  }
  lines.push(SEO_MARKER_END);
  return lines.join('\n');
}

function processOne(file) {
  const html = fs.readFileSync(file.abs, 'utf8');
  if (!/<\/head>/i.test(html)) return null;

  const pageType = detectPageType(file);
  const rawTitle = extractTitle(html);
  const description = extractMetaDescription(html);
  const cleanTitle = deriveCleanTitle(rawTitle) || extractH1(html) || file.rel.replace(/\.html$/i, '');
  const canonicalUrl = urlFor(file);
  const ogImage = DEFAULT_OG;

  const jsonLdBlocks = [];
  const breadcrumb = buildBreadcrumb(file, pageType, cleanTitle);
  if (breadcrumb) jsonLdBlocks.push(breadcrumb);

  if (pageType === PAGE_TYPE.TOP5) {
    const products = extractTop5Products(html);
    const il = buildItemList(file, cleanTitle, products, description);
    if (il) jsonLdBlocks.push(il);
    jsonLdBlocks.push(buildArticleSchema(file, cleanTitle, description, null));
  } else if (
    pageType === PAGE_TYPE.NEWS_ARTICLE ||
    pageType === PAGE_TYPE.NEWS_HUB
  ) {
    const localImg = extractFirstImage(html);
    const fullImg = localImg && /^https?:/.test(localImg)
      ? localImg
      : localImg
        ? `${SITE}${localImg.startsWith('/') ? '' : '/'}${localImg}`
        : null;
    jsonLdBlocks.push(buildArticleSchema(file, cleanTitle, description, fullImg));
  } else if (pageType === PAGE_TYPE.CONDITION || pageType === PAGE_TYPE.ABOUT) {
    jsonLdBlocks.push(buildArticleSchema(file, cleanTitle, description, null));
  } else if (pageType === PAGE_TYPE.CATALOG || pageType === PAGE_TYPE.CONDITION_HUB) {
    jsonLdBlocks.push(buildCollectionSchema(file, cleanTitle, description));
  }

  let out = html;

  // Strip any prior pass output to keep the operation idempotent. Also eat the
  // optional surrounding whitespace/newline so we don't accumulate a blank line.
  const escMarker = SEO_MARKER_START.replace(/[*+?^${}()|[\]\\]/g, '\\$&');
  const escMarkerEnd = SEO_MARKER_END.replace(/[*+?^${}()|[\]\\]/g, '\\$&');
  out = out.replace(
    new RegExp(`\\s*${escMarker}[\\s\\S]*?${escMarkerEnd}\\s*`, 'g'),
    '\n'
  );

  // Strip conflicting canonical / OG / twitter image tags from the original templates
  // (we own these now). Leaves og:title / description / type alone.
  out = out.replace(/[ \t]*<link\s+rel="canonical"[^>]*>\s*\r?\n?/gi, '');
  out = out.replace(/[ \t]*<meta\s+property="og:url"[^>]*>\s*\r?\n?/gi, '');
  out = out.replace(/[ \t]*<meta\s+property="og:image"[^>]*>\s*\r?\n?/gi, '');
  out = out.replace(/[ \t]*<meta\s+name="twitter:image"[^>]*>\s*\r?\n?/gi, '');

  // Add alt text to images with missing or empty alt attribute. Skip news pages
  // where image-heavy auto-generated content already includes alt attrs.
  if (pageType !== PAGE_TYPE.NEWS_ARTICLE) {
    out = fillImageAltText(out, cleanTitle);
  }

  // Inject the new managed block right before </head>.
  const block = buildInjectionBlock({ canonicalUrl, ogImage, jsonLdBlocks });
  out = out.replace(/<\/head>/i, `${block}\n</head>`);

  return out !== html ? out : null;
}

function main() {
  const files = listTargetFiles();
  console.log(`SEO pass: scanning ${files.length} files`);
  let updated = 0;
  let scanned = 0;
  let typeCounts = {};
  for (const f of files) {
    scanned++;
    const t = detectPageType(f);
    typeCounts[t] = (typeCounts[t] || 0) + 1;
    try {
      const updatedHtml = processOne(f);
      if (updatedHtml != null) {
        fs.writeFileSync(f.abs, updatedHtml);
        updated++;
      }
    } catch (e) {
      console.warn(`  skip ${f.scope}/${f.rel}: ${e.message}`);
    }
  }
  console.log(`Updated ${updated}/${scanned} files. By type:`);
  for (const [t, n] of Object.entries(typeCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${t.padEnd(16)} ${n}`);
  }
  if (fs.existsSync(PUBLIC_DIR)) {
    console.log(`Run "node scripts/copy-static-to-next.js" to sync apps/web/public.`);
  }
}

main();
